### ISSUE TITLE
gcc: Fehler: nicht erkannte Kommandozeilenoption »-rdynamic«

### ISSUE THREAD

**Issue by jxsl13** [upTee/upTee#82]
http://stackoverflow.com/questions/10599038/can-i-skip-cmake-compiler-tests-or-avoid-error-unrecognized-option-rdynamic

on windows server via cygwin.

**Comment by SushiTee** [comment]
I don't get how this is related to upTee. Please give more information.

**Comment by jxsl13** [comment]
Yeah, I was trying to compile uwsgi on a windows server via cygwin and got that error message.
It has less to do with the project itself than with setting up a working project environment.

**Comment by SushiTee** [comment]
I never tried building uwsgi on a windows server.
Anyway this is a problem of uwsgi and cannot be fixed here. You should probably state your problem here: https://github.com/unbit/uwsgi
