### ISSUE TITLE
In settings and votes it is possible to add linebreaks

### ISSUE THREAD

**Issue by abck** [upTee/upTee#83]
procedure:
- start Firefox
- go to the Uptee "Edit Settings"-Page
- right-click on an input box
- click on "Inspect Element"
- change '<input' to '<textarea'
- profit

**Comment by east** [comment]
```
splitlines()[0]
```
On empty strings gives an out of range error. Happens on empty fields e.g. password

**Comment by SushiTee** [comment]
hopefully fixed due to https://github.com/upTee/upTee/commit/8c1452c47defe7c13c0de5c2c8908cd14df2f45d now
