### ISSUE TITLE
Support for map specific configs

### ISSUE THREAD

**Issue by jxsl13** [upTee/upTee#85]
I'd like to suggest the possibility of adding map specific configs

Of course it would be kind of hard to still guarantee a high security in order to not make the whole system vulnerable due to the config's contents

**Comment by SushiTee** [comment]
might be possible by checking against the "allowed" settings from the mod itself.
An option to store different personal settings as presets would be perfect for this I think.

**Comment by jxsl13** [comment]
I actually meant the mapname.cfg files in the maps folder to be able to upload them with the map itself

and then to be checked against allowed commands

**Comment by abck** [comment]
@jxsl13 vanilla does not support that, thats mod specific

**Comment by SushiTee** [comment]
it doesn't matter if a mod supports this or not. Uptee would do those checks. Of course if you change the map ingame the map specific changes wouldn't apply.
Well I dont like the idea of making those settings only map specific. A general upload function for settings would be more useful I think. This would work great with a little website function to change the map.
