### ISSUE TITLE
readme.txt

### ISSUE THREAD

**Issue by jxsl13** [upTee/upTee#89]
Hey there, it's me again ._. more or less the only person using this really good hosting environment.

I think that server admins should be able to read the added readme.txt in the modpack for example to be able to understand how commands work and what they do or what the mod is about and so on :)

**Comment by SushiTee** [comment]
well in most cases the readme doesn't contain any of those information. But when uploading a mod it might be a good option to enter something about the mod.

**Comment by jxsl13** [comment]
maybe some kinda info.txt

**Comment by SushiTee** [comment]
why bother creating a txt?

**Comment by jxsl13** [comment]
hm because it's the standard file on most operating systems?

2015-02-05 11:39 GMT+01:00, SushiTee <notifications@github.com>:

**Comment by SushiTee** [comment]
nobody is writing a readme files for a mod. It's easier to just put the mod description when actually uploading the mod

**Comment by jxsl13** [comment]
well, that was my second thought about what you could mean :D and yeah true

SushiTee <notifications@github.com> schrieb am Thu Feb 05 2015 at 13:15:04:
