### ISSUE TITLE
Feature: Admin Contact/ Private Messages System

### ISSUE THREAD

**Issue by jxsl13** [upTee/upTee#90]
Like the header already lets suggest

I'd really like to have a way with my users to communicate with each other as well as to contact the admin if there are som kind of problems :)

what do you think?

**Comment by SushiTee** [comment]
not sure about this since this is no forum.
The users can post comments to blog entries or contact the admin directly via mail

**Comment by jxsl13** [comment]
or simply some kind of irc-like support chat :O where the history is saved,
cuz in irc you gotta be online the whole time in order to get to know what
questions ppl have.


2015-02-08 3:29 GMT+01:00 SushiTee <notifications@github.com>:

**Comment by SushiTee** [comment]
nah too much useless traffic and the website is not to chat.
