### ISSUE TITLE
Bug? Server start fails due to failure of copying the server files&stuff

### ISSUE THREAD

**Issue by jxsl13** [upTee/upTee#91]
http://pastebin.com/2maLniXE

due to some kind of constellation, I happened to produce the error that there is no such file "generated.cfg" to be found in a specific server directory.
I didn't actually change stuff manually, only via the webinterface to produce that error.

**Comment by SushiTee** [comment]
weird... and the file is actually missing? maybe there are some missing rights?

**Comment by jxsl13** [comment]
the whole folder seems to be missing when I look there via ftp

**Comment by SushiTee** [comment]
weird oO

How often did it happen?

**Comment by jxsl13** [comment]
it's the first time it happened. Well of course it'd be easy to delete the server and make a new one in the admin backend, but it wouldn't fix the cause of the problem.

**Comment by SushiTee** [comment]
that's true. The question is: What is the cause?
