### ISSUE TITLE
Changing server owner while the server's running seems to cause the server to be shown in sidebar even tho the owner is changed back to the old one

### ISSUE THREAD

**Issue by jxsl13** [upTee/upTee#92]
I changed the ownership of a vanilla server to myself in order to edit some configs/settings, saved it and changed the owner again to one of my users. Somehow the server ist still shown in the right sidebar which should actually only contain my own servers. Well, one thing is clear and that is that I am not able to edit he settings of that server anymore, because I am not the owner, so hopefully my explanation contains enough hints for you to find a solution :)

Greets jxsl13

**Comment by SushiTee** [comment]
Doesn't make sense and doesn't happen on my installation. NOthing should be cached there. Did you reload the page?
If you don't reload the page the server is ofc still visible there but you souldn't be able to change anything there.

**Comment by jxsl13** [comment]
well, I reloaded the page like 500 times and it still shows in my sidebar.
![1](https://cloud.githubusercontent.com/assets/371944/6199853/8dc54db8-b45c-11e4-890d-97fc8539f00f.png)
![2](https://cloud.githubusercontent.com/assets/371944/6199854/8dca310c-b45c-11e4-80df-edf92316dc51.png)

**Comment by SushiTee** [comment]
can it be that you are set to be moderator ffor that server?
For own server it should not show the Owner

**Comment by jxsl13** [comment]
well, now I get it, I'm really set as server moderator :) with no actual server management rights

**Comment by SushiTee** [comment]
good :)
